ALTER TABLE "StaffProfile"
  ADD COLUMN "dateOfBirth" TIMESTAMP(3),
  ADD COLUMN "addressLine1" TEXT,
  ADD COLUMN "addressLine2" TEXT,
  ADD COLUMN "suburb" TEXT,
  ADD COLUMN "state" TEXT,
  ADD COLUMN "postcode" TEXT,
  ADD COLUMN "emergencyContactName" TEXT,
  ADD COLUMN "emergencyContactRelationship" TEXT,
  ADD COLUMN "emergencyContactPhone" TEXT,
  ADD COLUMN "employmentType" TEXT,
  ADD COLUMN "payType" TEXT,
  ADD COLUMN "payRateCents" INTEGER,
  ADD COLUMN "payAward" TEXT,
  ADD COLUMN "taxFileNumber" TEXT,
  ADD COLUMN "taxResidencyStatus" TEXT,
  ADD COLUMN "taxFreeThreshold" BOOLEAN,
  ADD COLUMN "hasStudyTrainingLoan" BOOLEAN,
  ADD COLUMN "superFundName" TEXT,
  ADD COLUMN "superFundAbn" TEXT,
  ADD COLUMN "superFundUsi" TEXT,
  ADD COLUMN "superMemberNumber" TEXT,
  ADD COLUMN "bankAccountName" TEXT,
  ADD COLUMN "bankBsb" TEXT,
  ADD COLUMN "bankAccountNumber" TEXT,
  ADD COLUMN "visaStatus" TEXT,
  ADD COLUMN "visaSubclass" TEXT,
  ADD COLUMN "visaExpiryDate" TIMESTAMP(3),
  ADD COLUMN "workRightsNotes" TEXT,
  ADD COLUMN "xeroEmployeeId" TEXT,
  ADD COLUMN "xeroPayrollCalendarId" TEXT,
  ADD COLUMN "xeroEarningsRateId" TEXT;

CREATE INDEX "StaffProfile_venue_idx" ON "StaffProfile"("venue");
CREATE INDEX "StaffProfile_xeroEmployeeId_idx" ON "StaffProfile"("xeroEmployeeId");
